### ISSUE TITLE
2.1.7版本下载不到

### ISSUE THREAD

**Issue by shanghaif** [archine/excel-demo#1]
<artifactId>tools-excel</artifactId>
<version>2.1.7</version>

**Comment by archine** [comment]
你好，2.1.7下午五点半刚发布的新版本，推荐先拉取2.1.5，两个小时后等中央仓库同步后即可拉取最新的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shanghaif"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月15日(星期五) 下午5:56
收件人:&nbsp;"archine/excel-demo"<excel-demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[archine/excel-demo] 2.1.7版本下载不到 (#1)





 
tools-excel
 2.1.7
